version: '2'
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/task_manager:cached
    ports:
      - 3000:3000
    volumes_from:
      - bundle_cache
    command: bash -c "bundle exec rails s -b '0.0.0.0' -p 3000"
    environment:
      BUNDLE_PATH: /bundle_cache
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      CI: ${CI}
      TRAVIS: ${TRAVIS}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
    stdin_open: true
    tty: true
  db:
    image: postgres:11.1-alpine
  bundle_cache:
    image: busybox
    volumes:
      - /bundle_cache
